package az.testup.enums;

public enum AuditAction {
    // Auth
    USER_LOGIN, USER_LOGIN_FAILED, USER_REGISTERED, PASSWORD_CHANGED,
    PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED,
    // User management
    USER_ROLE_CHANGED, USER_DELETED, USER_TOGGLED, USER_EXAM_ASSIGNED,
    // Exam lifecycle
    EXAM_CREATED, EXAM_UPDATED, EXAM_DELETED, EXAM_STATUS_CHANGED,
    EXAM_SITE_PUBLISHED, EXAM_SITE_UNPUBLISHED, EXAM_PRICE_CHANGED,
    EXAM_ACCESS_CODE_GENERATED, EXAM_PURCHASED,
    EXAM_PDF_DOWNLOADED, EXAM_RESULTS_EXPORTED,
    // Exam session
    EXAM_STARTED, EXAM_SUBMITTED,
    // Submission / grading
    SUBMISSION_MANUAL_GRADED, SUBMISSION_HIDDEN,
    // Collaborative exam
    COLLABORATIVE_EXAM_CREATED, COLLABORATIVE_COLLABORATOR_ADDED,
    COLLABORATIVE_DRAFT_SUBMITTED, COLLABORATIVE_DRAFT_APPROVED, COLLABORATIVE_DRAFT_REJECTED,
    // Subject / Content
    SUBJECT_ADDED, SUBJECT_DELETED, SUBJECT_UPDATED,
    TOPIC_ADDED, TOPIC_DELETED,
    // Banner / Tag
    BANNER_CREATED, BANNER_UPDATED, BANNER_DELETED,
    TAG_CREATED, TAG_DELETED,
    // Template / Section / Subtitle
    TEMPLATE_CREATED, TEMPLATE_UPDATED, TEMPLATE_DELETED,
    TEMPLATE_SUBTITLE_CREATED, TEMPLATE_SUBTITLE_UPDATED, TEMPLATE_SUBTITLE_DELETED,
    TEMPLATE_SECTION_CREATED, TEMPLATE_SECTION_UPDATED, TEMPLATE_SECTION_DELETED,
    // Question bank
    BANK_SUBJECT_CREATED, BANK_SUBJECT_UPDATED, BANK_SUBJECT_DELETED,
    BANK_QUESTION_CREATED, BANK_QUESTION_UPDATED, BANK_QUESTION_DELETED,
    // AI
    AI_QUESTIONS_GENERATED, AI_EXAM_GENERATED,
    // Contact
    CONTACT_READ, CONTACT_REPLIED, CONTACT_DELETED,
    // Notification
    NOTIFICATION_SENT,
    // Payment / Subscription
    PAYMENT_INITIATED, PAYMENT_FAILED, PAYMENT_AUTO_RECOVERED,
    PAYMENT_PROVIDER_ERROR, PAYMENT_UNAUTHORIZED_ACCESS, PAYMENT_STORED_CARD_USED,
    PAYMENT_REVERSED, PAYMENT_RATE_LIMITED,
    ORDER_CANCELLED, ORDER_ORPHANED,
    SUBSCRIPTION_PURCHASED, SUBSCRIPTION_SWITCHED, SUBSCRIPTION_RENEWED,
    SUBSCRIPTION_ASSIGNED_MANUAL, SUBSCRIPTION_CANCELLED, SUBSCRIPTION_GIFTED,
    PLAN_CREATED, PLAN_UPDATED, PLAN_DELETED,
    // System
    SYSTEM_ERROR
}
