package az.testup.enums;

public enum AuditAction {
    // Auth
    USER_LOGIN, USER_LOGIN_FAILED, USER_REGISTERED, PASSWORD_CHANGED,
    // User management
    USER_ROLE_CHANGED, USER_DELETED, USER_TOGGLED, USER_EXAM_ASSIGNED,
    // Exam lifecycle
    EXAM_CREATED, EXAM_UPDATED, EXAM_DELETED, EXAM_STATUS_CHANGED,
    EXAM_SITE_PUBLISHED, EXAM_SITE_UNPUBLISHED,
    // Exam session
    EXAM_STARTED, EXAM_SUBMITTED,
    // Subject/Content
    SUBJECT_ADDED, SUBJECT_DELETED, TOPIC_ADDED, TOPIC_DELETED,
    // Notification
    NOTIFICATION_SENT,
    // Payment / Subscription
    SUBSCRIPTION_PURCHASED, SUBSCRIPTION_SWITCHED, SUBSCRIPTION_ASSIGNED_MANUAL, SUBSCRIPTION_CANCELLED,
    // System
    SYSTEM_ERROR
}
